@startuml
class Деканат{
    +Списки студентов : string
    +Зачётные книжки: string
    +Успеваемость : integer
    +Отчислять / принимать студентов()
    +Переводить студентов с курса на курс()
    +Переводить студентов с группы в группу()
}