@startuml
participant Студент
participant Деканат
participant Вуз
Студент -> Деканат: 1.Принести диплом и результаты ЕГЭ
Деканат -> Студент: 2. Принять на обработку данные
Деканат -> Вуз: 3. Сообщить о количество студентов, подавщих документы
Деканат -> Студент: 4. Сообщить об успешном приёме
Студент -> Вуз: 5. Прийти на пары
@enduml