@startuml
node Студент{
    artifact "Жалобы на преподаваталей"
}

node Деканат{
    artifact "Информация о приподователя и студентах"
}

Деканат 0--0 Студент : Сообщение жалобы
node Вуз{
    node "Архив преподователей"{
        artifact "Преподаватель"
    }
}

Вуз --0 Деканат: Передача жалобы
@enduml